services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - metrics
    labels:
      - com.github.nginx-proxy.nginx

  acme-companion:
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-acme
    restart: unless-stopped
    volumes_from:
      - nginx-proxy
    depends_on:
      - nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - acme:/etc/acme.sh
    environment:
      - DEFAULT_EMAIL=thomleenman@gmail.com
      - NGINX_PROXY_CONTAINER=nginx-proxy
    networks:
      - metrics

  nginx:
    container_name: nginx
    image: nginx:1.27.0
    restart: unless-stopped
    depends_on:
      - nginx-proxy
      - acme-companion
      - frontend
      - backend
    volumes:
      - '/home/ict/nginx.conf:/etc/nginx/nginx.conf'
      - '/home/ict/nginx-client.conf:/etc/nginx/conf.d/default.conf:ro'
    environment:
      - VIRTUAL_HOST=chess.lnmn.nl
      - VIRTUAL_PORT=443
      - LETSENCRYPT_HOST=chess.lnmn.nl
    networks:
      - metrics
      - application

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    networks:
      - application
    
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    restart: unless-stopped